export const styles = {
  appContainer: { backgroundColor: '#f8fafc', minHeight: '100vh', fontFamily: 'sans-serif' },
  navbar: { backgroundColor: '#4f46e5', color: 'white', padding: '10px 40px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  navLeft: { display: 'flex', alignItems: 'center', gap: '20px' },
  stationTag: { fontSize: '0.85rem', opacity: 0.9 },
  content: { padding: '30px 60px' },
  pageHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '30px' },
  title: { margin: 0, fontSize: '1.8rem', color: '#1e293b' },
  subtitle: { margin: '5px 0 0 0', color: '#64748b' },
  mainGrid: { display: 'grid', gridTemplateColumns: '1.5fr 1fr', gap: '25px' },
  leftCol: { display: 'flex', flexDirection: 'column' },
  rightCol: { display: 'flex', flexDirection: 'column' },
  card: { backgroundColor: 'white', borderRadius: '12px', padding: '20px', boxShadow: '0 1px 3px rgba(0,0,0,0.1)', marginBottom: '20px', position: 'relative' },
  cardHeader: { display: 'flex', justifyContent: 'space-between', marginBottom: '20px' },
  orderTitle: { display: 'flex', gap: '12px', alignItems: 'center' },
  iconChip: { fontSize: '1.5rem', backgroundColor: '#f1f5f9', padding: '8px', borderRadius: '8px' },
  statusBadge: { backgroundColor: '#dcfce7', color: '#166534', padding: '4px 10px', borderRadius: '6px', fontSize: '0.75rem', fontWeight: 'bold', height: 'fit-content' },
  progressSection: { marginTop: '10px' },
  progressLabels: { display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem', color: '#64748b', marginBottom: '8px' },
  progressBarBg: { backgroundColor: '#f1f5f9', height: '10px', borderRadius: '10px', overflow: 'hidden' },
  progressBarFill: { backgroundColor: '#4f46e5', height: '100%', transition: 'width 0.3s' },
  projectTag: { position: 'absolute', bottom: '10px', right: '10px', color: 'white', padding: '3px 10px', borderRadius: '4px', fontSize: '0.7rem', fontWeight: 'bold' },
  scanCard: { textAlign: 'center', padding: '40px' },
  barcodeIcon: { fontSize: '3rem', color: '#cbd5e1', marginBottom: '10px' },
  scanForm: { display: 'flex', gap: '10px', justifyContent: 'center', marginTop: '20px' },
  input: { width: '70%', padding: '12px', borderRadius: '8px', border: '1px solid #ddd', outline: 'none' },
  btnRegister: { backgroundColor: '#4f46e5', color: 'white', border: 'none', padding: '0 20px', borderRadius: '8px', cursor: 'pointer' },
  kpiRow: { display: 'flex', gap: '15px', marginBottom: '20px' },
  kpiCard: { backgroundColor: 'white', flex: 1, padding: '15px', borderRadius: '12px', textAlign: 'center', boxShadow: '0 1px 3px rgba(0,0,0,0.1)' },
  kpiValue: { fontSize: '2rem', fontWeight: 'bold', color: '#1e293b', marginTop: '5px' },
  cardHeaderSmall: { fontWeight: 'bold', marginBottom: '15px', color: '#334155', borderBottom: '1px solid #e2e8f0', paddingBottom: '10px' },
  lastScanDetails: { backgroundColor: '#f8fafc', padding: '15px', borderRadius: '8px' },
  detailRow: { padding: '10px 0', borderBottom: '1px solid #e2e8f0', display: 'flex', flexDirection: 'column', gap: '4px' },
  inspectBadge: { backgroundColor: '#fef3c7', color: '#92400e', padding: '4px 8px', borderRadius: '4px', fontSize: '0.7rem', fontWeight: 'bold', width: 'fit-content' },
  btnHistory: { width: '100%', marginTop: '15px', padding: '10px', border: '1px solid #e2e8f0', borderRadius: '8px', backgroundColor: 'white', cursor: 'pointer', color: '#64748b', fontWeight: 'bold' },
  inputLabel: { display: 'block', marginBottom: '5px', fontSize: '0.85rem', fontWeight: 'bold', color: '#64748b' },
  selectInput: { width: '100%', padding: '12px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '1rem', outline: 'none', backgroundColor: '#f8fafc' },
  errorMessage: { color: '#ef4444', backgroundColor: '#fee2e2', padding: '10px', borderRadius: '8px', marginTop: '15px', fontSize: '0.9rem', fontWeight: 'bold' },
  historyList: { marginTop: '15px', maxHeight: '250px', overflowY: 'auto', backgroundColor: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0', padding: '10px' },
  historyItem: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '10px 5px', borderBottom: '1px solid #e2e8f0', fontSize: '0.9rem' },
  historyEmpty: { textAlign: 'center', color: '#94a3b8', padding: '15px 0', fontSize: '0.9rem' },
  serialList: { maxHeight: '300px', overflowY: 'auto', backgroundColor: '#f8fafc', borderRadius: '8px', border: '1px solid #e2e8f0' },
  serialItem: { display: 'flex', justifyContent: 'space-between', padding: '10px 15px', borderBottom: '1px solid #e2e8f0', fontSize: '0.9rem' },
  serialCode: { fontWeight: 'bold', color: '#1e293b' },
  serialStatus: { backgroundColor: '#dcfce7', color: '#166534', padding: '3px 8px', borderRadius: '5px', fontSize: '0.7rem' },
};